---
title: "Trabajo 2"
author: "Elisa Matte y Leandro Suarez"
format: html
editor: visual
---

# Escala y Alfa de Chronbach

```{r}
# Instalar y cargar paquetes necesarios.
install.packages("pacman")
install.packages("psych")

library("pacman")
library("psych")
library("dplyr")
library("sjlabelled")
pacman::p_load(tidyverse,   # manipulacion datos.
               sjPlot,      # tablas.
               stargazer,   # tablas.
               confintr,    # IC.
               gginference, # visualizacion .
               rempsyc,     # reporte.
               broom,       # varios.
               sjmisc,      # para descriptivos .
               sjlabelled,  # etiquetas.
               knitr)

## Desactivar notación científica
options(scipen = 999) 

## Limpiar entorno de trabajo.
rm(list = ls()) 

## Visualizar objetos de carpeta "Input".
list.files("Input")
```

```{r}
## Cargar base de datos ENJUV 2022 (base de jovenes).
base <- read.dta("Encuesta_ Jovenes.dta")
dim(base)
ls(base) 

## Visualizar variables.
view(base$P102_2) # Frecuencia de la dificultad para controlar la preocupación
view(base$P102_5) # Frecuencia de la dificultad para quedarse dormido/a

base$P102_2 <- na_if(base$P102_2, 99) # Tratar los 99 (NS/NR) como NA.
base$P102_5 <- na_if(base$P102_5, 99) # Tratar los 99 (NS/NR) como NA.

esc_data <- base %>% select(P102_2, 
                      P102_5)

## Eliminar casos perdidos (NA).
sum(is.na(esc_data)) # Cantidad de casos perdidos.

esc_data <-na.omit(esc_data) 
dim(esc_data)
view(esc_data)

## Renombrar ambas variables.
sjlabelled::get_label(esc_data)

esc_data <- esc_data %>% rename("preocupacion"=P102_2)
esc_data <- esc_data %>% rename("insomnio"=P102_5)

sjlabelled::get_label(esc_data)

## Re-etiquetar ambas variables 
esc_data$preocupacion <- sjlabelled::set_label(esc_data$preocupacion, label = "Frecuencia : Preocupacion")
sjlabelled::get_label(esc_data$preocupacion)

esc_data$insomnio <- sjlabelled::set_label(esc_data$insomnio, label = "Frecuencia : Insomnio")
sjlabelled::get_label(esc_data$insomnio)
```

```{r}
## Convertir las variables a numéricas para la escala y el Alfa Chronbach.
cor(esc_data)

esc_data <- esc_data %>%
  mutate(
    preocupacion_num = as.numeric(as_factor(preocupacion)),
    insomnio_num = as.numeric(as_factor(insomnio))
  )

esc_data <- esc_data %>%
  rowwise() %>%
  mutate(salud_mental = sum(preocupacion_num, insomnio_num, na.rm = TRUE)) %>%
  ungroup()

summary(esc_data$salud_mental)

# Aplicar Alfa de Chronbach
psych::alpha(esc_data)

```
